 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contests", type: :request do
  
  # Contest. As you add validations to Contest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Contest.create! valid_attributes
      get contests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      contest = Contest.create! valid_attributes
      get contest_url(contest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_contest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      contest = Contest.create! valid_attributes
      get edit_contest_url(contest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Contest" do
        expect {
          post contests_url, params: { contest: valid_attributes }
        }.to change(Contest, :count).by(1)
      end

      it "redirects to the created contest" do
        post contests_url, params: { contest: valid_attributes }
        expect(response).to redirect_to(contest_url(Contest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Contest" do
        expect {
          post contests_url, params: { contest: invalid_attributes }
        }.to change(Contest, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contests_url, params: { contest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contest" do
        contest = Contest.create! valid_attributes
        patch contest_url(contest), params: { contest: new_attributes }
        contest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the contest" do
        contest = Contest.create! valid_attributes
        patch contest_url(contest), params: { contest: new_attributes }
        contest.reload
        expect(response).to redirect_to(contest_url(contest))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        contest = Contest.create! valid_attributes
        patch contest_url(contest), params: { contest: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested contest" do
      contest = Contest.create! valid_attributes
      expect {
        delete contest_url(contest)
      }.to change(Contest, :count).by(-1)
    end

    it "redirects to the contests list" do
      contest = Contest.create! valid_attributes
      delete contest_url(contest)
      expect(response).to redirect_to(contests_url)
    end
  end
end
