 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/evaluations", type: :request do
  
  # Evaluation. As you add validations to Evaluation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Evaluation.create! valid_attributes
      get evaluations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      evaluation = Evaluation.create! valid_attributes
      get evaluation_url(evaluation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_evaluation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      evaluation = Evaluation.create! valid_attributes
      get edit_evaluation_url(evaluation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Evaluation" do
        expect {
          post evaluations_url, params: { evaluation: valid_attributes }
        }.to change(Evaluation, :count).by(1)
      end

      it "redirects to the created evaluation" do
        post evaluations_url, params: { evaluation: valid_attributes }
        expect(response).to redirect_to(evaluation_url(Evaluation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Evaluation" do
        expect {
          post evaluations_url, params: { evaluation: invalid_attributes }
        }.to change(Evaluation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post evaluations_url, params: { evaluation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested evaluation" do
        evaluation = Evaluation.create! valid_attributes
        patch evaluation_url(evaluation), params: { evaluation: new_attributes }
        evaluation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the evaluation" do
        evaluation = Evaluation.create! valid_attributes
        patch evaluation_url(evaluation), params: { evaluation: new_attributes }
        evaluation.reload
        expect(response).to redirect_to(evaluation_url(evaluation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        evaluation = Evaluation.create! valid_attributes
        patch evaluation_url(evaluation), params: { evaluation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested evaluation" do
      evaluation = Evaluation.create! valid_attributes
      expect {
        delete evaluation_url(evaluation)
      }.to change(Evaluation, :count).by(-1)
    end

    it "redirects to the evaluations list" do
      evaluation = Evaluation.create! valid_attributes
      delete evaluation_url(evaluation)
      expect(response).to redirect_to(evaluations_url)
    end
  end
end
